export const STUDY_WEIGHT = 0.5

export const STUDY_MODES = [
  "drill",
  "case",
  "recall",
  "weak_area",
  "teach_back",
] as const

export type StudyMode = (typeof STUDY_MODES)[number]

export const AREA_LABELS: Record<string, string> = {
  "nlp-i": "NP I — Community Health",
  "nlp-ii": "NP II — Mother & Child",
  "nlp-iii": "NP III — Adult Health",
  "nlp-iv": "NP IV — Adult Health (Part 2)",
  "nlp-v": "NP V — Mental Health & Psych",
}

export const CONCEPT_CHECKLISTS: Record<string, Record<string, string[]>> = {
  "nlp-i": {
    "Community Health Nursing": [
      "Community health nursing roles: provider, educator, manager, advocate",
      "Community assessment: windshield survey, vital statistics, epidemiological data",
      "Health promotion and disease prevention strategies at community level",
      "Home visit process: planning, conducting, documentation, follow-up",
      "Case management in community settings: coordination, referral, continuity of care",
      "Barriers to healthcare access: socioeconomic, cultural, geographic factors",
      "Community-based rehabilitation principles and nursing interventions",
      "Philippine health programs: PhilHealth, 4Ps, RHU services",
    ],
    "Epidemiology & Biostatistics": [
      "Incidence vs prevalence: definitions, calculation, and clinical significance",
      "Morbidity and mortality rates: computation and interpretation for nursing practice",
      "Epidemic vs endemic vs pandemic: distinctions and public health response",
      "Study designs: cohort, case-control, cross-sectional — strengths and limitations",
      "Sensitivity, specificity, predictive values — interpreting screening test results",
      "Confounding variables and bias in epidemiological studies",
      "Vital statistics: birth rate, death rate, infant mortality rate computation",
      "Health indicators: DALY, QALY, life expectancy — meaning and nursing relevance",
    ],
    "Family Nursing": [
      "Family nursing assessment: genogram, eco-map, family life cycle stage",
      "Family dynamics: roles, communication patterns, decision-making structures",
      "Family systems theory: boundaries, hierarchy, homeostasis, feedback loops",
      "Family-centered care: principles, interventions, and nursing implications",
      "Caring for families with chronic illness: burden, coping, caregiver fatigue",
      "Family crisis intervention: assessment, short-term therapy, referral",
      "Prenatal family assessment: readiness for parenthood, support systems",
      "Bereavement care: stages of grief, anticipatory grief, nursing support",
    ],
    "Maternal & Child Health": [
      "Prenatal care schedule: prenatal visits, screening tests, danger signs",
      "Maternal nutrition during pregnancy: iron, folic acid, calcium requirements",
      "Childbearing myths vs evidence-based practice in Philippine setting",
      "Postpartum assessment: fundal height, lochia, perineal care, mood screening",
      "Newborn screening: congenital hypothyroidism, PKU, galactosemia, hearing",
      "Breastfeeding benefits and techniques: latch, positioning, common problems",
      "Growth and development milestones: Erikson, Piaget, Denver developmental screening",
      "Immunization schedule (Philippines): antigens, timing, contraindications, AEFI",
    ],
    "Immunization & Vaccine-Preventable Diseases": [
      "EPI (Expanded Program on Immunization): antigens, schedule, cold chain",
      "Live vs inactivated vaccines: storage, handling, contraindications",
      "Herd immunity: concept, threshold, and public health implications",
      "Vaccine adverse events following immunization (AEFI): types, reporting, management",
      "Filipino immunization beliefs: addressing vaccine hesitancy with cultural sensitivity",
      "Tetanus prophylaxis: wound management, Td booster schedule, pregnancy considerations",
      "Measles, polio, hepatitis B — pathophysiology, prevention, and nursing care",
      "Universal immunization coverage: challenges in remote and underserved areas",
    ],
    "Nutrition in Community": [
      "Nutritional assessment methods: dietary recall, food frequency, anthropometry",
      "Malnutrition in children: stunting, wasting, underweight — DOH data and interventions",
      "Breastfeeding support: exclusive breastfeeding promotion, milk banks, peer counseling",
      "Feeding programs: supplementary feeding, therapeutic feeding, community kitchen",
      "Micronutrient supplementation: vitamin A, iron, iodine — deficiency and prevention",
      "Obesity prevention: community-based interventions, school health programs",
      "Cultural food practices in the Philippines: dietary beliefs, food taboos, nutrition education",
      "Therapeutic diets and community-based nutrition rehabilitation",
    ],
    "Environmental & Occupational Health": [
      "Environmental health hazards: air pollution, water contamination, vector-borne diseases",
      "Water safety: chlorination, boiling, filtration — community-level interventions",
      "Solid waste management: segregation, disposal, health effects of improper waste handling",
      "Occupational health nursing: workplace hazards, OHSN, OWWA programs",
      "Ergonomic assessment and musculoskeletal injury prevention in workers",
      "Noise-induced hearing loss: prevention, monitoring, workplace standards",
      "Heat-related illness: recognition, first aid, occupational prevention strategies",
      "Occupational health legislation: RA 7875, OSHS, workers' compensation",
    ],
    "Primary Health Care & DOH Programs": [
      "Philippine Primary Care Act (RA 11223): Konsulta, essential health services package",
      "PhilHealth coverage: benefit packages, Z benefits, point-of-care limits",
      "4Ps (Pantawid Pamilyang Pilipino Program): health and education conditionalities",
      "Barangay Health System: BHW roles, RHU services, community-based disease surveillance",
      "Communicable disease control: surveillance, contact tracing, quarantine protocols",
      "Non-communicable disease prevention: lifestyle modification, community screening",
      "Mental health in the community: RA 11036, community-based mental health programs",
      "DOH health campaigns: dengue, tuberculosis, HIV/AIDS, substance abuse prevention",
    ],
  },
  "nlp-ii": {
    "Antepartum Care": [
      "Prenatal assessment: Leopold's maneuvers, fundal height measurement, fetal heart tones",
      "Physiological changes in pregnancy: cardiovascular, respiratory, hematologic adaptations",
      "Prenatal screening: ultrasound dating, maternal serum screening, NIPT, glucose tolerance test",
      "Danger signs in pregnancy: vaginal bleeding, severe headache, epigastric pain, visual changes",
      "Preeclampsia/eclampsia: pathophysiology, signs, HELLP syndrome, magnesium sulfate protocol",
      "Gestational diabetes: screening, management, insulin therapy, fetal surveillance",
      "Rh incompatibility: Rh-negative mother, antibody screening, RhoGAM administration",
      "Antepartum fetal surveillance: non-stress test, biophysical profile, Doppler velocimetry",
    ],
    "Intrapartum Care": [
      "Stages of labor: assessment, duration, nursing interventions per stage",
      "Fetal heart rate monitoring: baseline, variability, accelerations, decelerations (types)",
      "Mechanisms of labor: engagement, descent, flexion, extension, external rotation",
      "Friedman's labor curve: active phase, deceleration phase, prolonged labor management",
      "Intrapartum complications: cord prolapse, shoulder dystocia, uterine rupture",
      "Pharmacological pain relief: epidural, systemic opioids, nitrous oxide — nursing care",
      "Non-pharmacological comfort measures: positioning, breathing, hydrotherapy, massage",
      "Operative delivery: vacuum extraction, forceps, cesarean section — nursing responsibilities",
    ],
    "Postpartum Care": [
      "Postpartum assessment: fundal height, lochia (color, amount, odor), perineum",
      "Involution of uterus: fundal descent, placental site healing timeline",
      "Postpartum hemorrhage: risk factors, active management of third stage, massage",
      "Postpartum infection: endometritis, wound infection, mastitis — signs and nursing care",
      "Postpartum mood disorders: baby blues vs postpartum depression vs psychosis",
      "Contraceptive counseling: options, contraindications, LAM method",
      "Breast engorgement: prevention, management, breast pumping techniques",
      "Postpartum health teaching: hygiene, activity, nutrition, danger signs, follow-up",
    ],
    "Newborn Care": [
      "Newborn assessment: APGAR scoring, gestational age assessment (Ballard score)",
      "Physiological adaptations at birth: transitional circulation, first breath, thermoregulation",
      "Newborn vital signs: normal ranges, respiratory rate, heart rate, temperature monitoring",
      "Hypoglycemia in newborns: risk factors, screening, management (early feeding, IV dextrose)",
      "Neonatal jaundice: physiologic vs pathologic, phototherapy, exchange transfusion criteria",
      "Newborn bathing, cord care, and skin care: evidence-based practices",
      "Kangaroo mother care: skin-to-skin contact, breastfeeding support, temperature regulation",
      "Newborn screening: congenital disorders, metabolic screening, hearing screening",
    ],
    "High-Risk Pregnancy": [
      "Hyperemesis gravidarum: assessment, IV fluid replacement, thiamine supplementation",
      "Placenta previa vs abruption placentae: differential diagnosis, management, nursing care",
      "Preterm labor: risk factors, tocolytic therapy, magnesium sulfate, corticosteroids",
      "Intrauterine growth restriction: etiology, surveillance, delivery planning",
      "Multiple gestations: complications, fetal monitoring, delivery considerations",
      "Rh isoimmunization: hemolytic disease of the newborn, intrauterine transfusion",
      "Infections in pregnancy: TORCH, UTI, Group B Streptococcus screening and prophylaxis",
      "Cesarean section: indications, preoperative and postoperative nursing care",
    ],
    "Gynecological Disorders": [
      "Menstrual disorders: amenorrhea, menorrhagia, dysmenorrhea — assessment and management",
      "Polycystic ovary syndrome (PCOS): pathophysiology, clinical presentation, treatment",
      "Endometriosis: symptoms, staging, pain management, surgical interventions",
      "Sexually transmitted infections: chlamydia, gonorrhea, syphilis, HPV — screening and treatment",
      "Cervical cancer screening: Pap smear, HPV testing, VIA, vaccination",
      "Pelvic inflammatory disease: etiology, complications, antibiotic therapy",
      "Uterine fibroids: symptom management, myomectomy vs hysterectomy indications",
      "Vulvar and vaginal disorders: infections, atrophy, lichen sclerosus — nursing care",
    ],
    "Pediatric Growth & Development": [
      "Growth assessment: weight, height, head circumference — percentile charts",
      "Developmental milestones: motor, language, cognitive, social — age-appropriate expectations",
      "Erikson's psychosocial stages: trust vs mistrust through adolescence",
      "Piaget's cognitive stages: sensorimotor through formal operations",
      "Play therapy types and developmental benefits for hospitalized children",
      "Anticipatory guidance: well-child visit topics per age group",
      "Adolescent development: puberty, body image, peer influence, autonomy",
      "Developmental red flags: when to refer for early intervention",
    ],
    "Pediatric Common Conditions": [
      "Febrile seizures: definition, management, parental education, recurrence risk",
      "Pediatric dehydration: assessment, ORS vs IV rehydration, monitoring",
      "Bronchiolitis: RSV, supportive care, oxygen therapy, when to intubate",
      "Pyloric stenosis: projectile vomiting, metabolic alkalosis, surgical correction",
      "Childhood asthma: triggers, stepwise therapy, inhaler technique education",
      "Congenital heart defects: ASD, VSD, Tetralogy of Fallot — assessment, shunting",
      "Pediatric oncology: leukemia presentation, chemotherapy nursing care, infection prevention",
      "Child abuse and neglect: recognition, mandatory reporting, documentation, safety planning",
    ],
  },
  "nlp-iii": {
    "Cardiovascular": [
      "Heart failure pathophysiology and nursing prioritization",
      "Myocardial infarction: STEMI vs NSTEMI recognition and immediate interventions",
      "Hypertension management: first-line meds and nursing monitoring",
      "Cardiac rhythm interpretation basics: sinus bradycardia, atrial fibrillation, ventricular tachycardia",
      "Post-MI complications: cardiogenic shock, mechanical complications, reinfarction",
      "Cardiac catheterization and CABG post-op nursing care",
      "Anticoagulation therapy: heparin vs warfarin, monitoring labs (aPTT, INR)",
      "Peripheral vascular disease: assessment and patient teaching",
    ],
    "Respiratory": [
      "COPD exacerbation: triggers, ABG interpretation, and nursing interventions",
      "Asthma pathophysiology: bronchospasm, inflammation, reversible airflow obstruction",
      "Pneumonia: community-acquired vs hospital-acquired, antibiotic selection principles",
      "Pulmonary embolism: risk factors, clinical signs, and emergency response",
      "Chest tube management: water seal, suction, and monitoring for complications",
      "Oxygen therapy: nasal cannula vs simple mask vs non-rebreather, FiO2 equivalents",
      "Mechanical ventilation: modes (AC, SIMV, CPAP), alarms, and weaning",
      "ABG interpretation: pH, PaCO2, HCO3, PaO2 — acid-base disorders",
    ],
    "Renal": [
      "Acute kidney injury: prerenal vs intrarenal vs postrenal, BUN:creatinine ratio",
      "Chronic kidney disease: stages, GFR, and conservative vs dialysis management",
      "Hemodialysis: access sites, complications (hypotension, infection, Disequilibrium)",
      "Peritoneal dialysis: catheter care, peritonitis signs, ultrafiltration",
      "Electrolyte imbalances: hyperkalemia, hyponatremia — ECG changes and interventions",
      "Fluid volume overload vs deficit: assessment findings and IV fluid selection",
      "Urinary tract infections: upper vs lower, complicated vs uncomplicated",
      "Renal calculi: types, pain management, lithotripsy, strainer instructions",
    ],
    "Endocrine": [
      "Diabetes mellitus Type 1 vs Type 2: pathophysiology, insulin types, onset/duration",
      "DKA vs HHS: labs, emergency management, insulin drip protocol",
      "Hypoglycemia: recognition, Rule of 15, glucagon administration",
      "Thyroid disorders: hyperthyroidism (Graves) vs hypothyroidism (Hashimoto), thyroid storm",
      "Adrenal insufficiency: Addison's vs Cushing's, cortisol replacement, crisis management",
      "Insulin administration: site rotation, lipodystrophy, storage, mixing insulin",
      "Blood glucose monitoring: target ranges, HbA1c interpretation, sick day rules",
      "Metabolic syndrome: components, risk factors, and nursing education",
    ],
    "Neurological": [
      "Stroke: ischemic vs hemorrhagic, NIHSS, tPA eligibility and time window",
      "Increased ICP: Cushing reflex, interventions (elevate HOB, mannitol, hypertonic saline)",
      "Seizure management: status epilepticus, safety precautions, antiepileptic drugs",
      "Spinal cord injury: neurogenic shock, autonomic dysreflexia, level-of-injury effects",
      "Glasgow Coma Scale: components and scoring, serial assessment importance",
      "Myasthenia gravis: crisis vs exacerbation, Tensilon test, plasmapheresis",
      "Parkinson's disease: levodopa/carbidopa, fall risk, progressive disability",
      "GBS: ascending paralysis, respiratory monitoring, IVIG vs plasmapheresis",
    ],
    "Gastrointestinal": [
      "Peptic ulcer disease: H. pylori, NSAIDs, PPI therapy, complications (perforation, hemorrhage)",
      "Cirrhosis: portal hypertension, ascites, esophageal varices, hepatic encephalopathy",
      "Pancreatitis: Ranson criteria, pain management, TPN indication",
      "Inflammatory bowel disease: UC vs Crohn's, complications, biologic therapy",
      "Colostomy vs ileostomy: stoma care, output patterns, dietary teaching",
      "GI bleeding: upper vs lower, NG tube decompression, endoscopy prep",
      "Hepatitis: viral types (A-E), transmission, labs (AST/ALT, bilirubin), isolation",
      "Bowel obstruction: mechanical vs functional (ileus), NG tube management",
    ],
    "Fluids & Electrolytes": [
      "Fluid volume deficit: dehydration assessment, oral rehydration vs IV replacement",
      "Fluid volume overload: pulmonary edema, diuretic therapy, fluid restriction",
      "Hypokalemia: ECG changes (U waves), digoxin toxicity risk, potassium replacement",
      "Hyperkalemia: peaked T waves, calcium gluconate, insulin/glucose, kayexalate",
      "Hyponatremia: causes (SIADH, psychogenic polydipsia), correction rate limits",
      "Hypernatremia: water deficit calculation, free water replacement",
      "Metabolic acidosis: anion gap, DKA, bicarbonate therapy indications",
      "Metabolic alkalosis: cause (NG suction, vomiting), saline-responsive vs resistant",
    ],
    "Musculoskeletal": [
      "Fracture care: neurovascular checks, compartment syndrome (5 P's), fat embolism",
      "Traction: skin traction vs skeletal traction, Buck's skin traction nursing care",
      "Cast care: wet cast dangers, bivalving, window creation, neurovascular assessment",
      "Joint replacement: DVT prophylaxis, ROM exercises, weight-bearing precautions",
      "Osteoporosis: DEXA scan interpretation, bisphosphonate therapy, fall prevention",
      "Arthritis: RA vs OA, joint preservation strategies, DMARD therapy",
      "Amputation: phantom limb pain, stump care, prosthetic fitting timeline",
      "CPM machine: indications, ROM settings, patient education",
    ],
    "Perioperative": [
      "Preoperative: informed consent, NPO guidelines, preop checklist, anxiety management",
      "Intraoperative: sterile technique, patient positioning, surgical safety checklist",
      "Postoperative hemorrhage: assessment, drain management, when to call surgeon",
      "Postoperative infection: SSI signs, antibiotic prophylaxis, wound assessment",
      "DVT/PE prevention: sequential compression devices, early ambulation, anticoagulation",
      "Postoperative ileus: NG tube management, bowel sound assessment, diet advancement",
      "Wound dehiscence vs evisceration: immediate management, emergency call",
      "Postop pain management: PCA, multimodal analgesia, rebound pain recognition",
    ],
  },
  "nlp-iv": {
    "Oncology Nursing": [
      "Cancer staging: TNM classification, stages I-IV, metastasis pathways",
      "Chemotherapy: mechanisms, cycle scheduling, dose-limiting toxicities",
      "Radiation therapy: external vs brachytherapy, skin care, radiation protection",
      "Neutropenic precautions: infection prevention, neutrophil count monitoring, reverse isolation",
      "Oncologic emergencies: superior vena cava syndrome, spinal cord compression, tumor lysis",
      "Pain management in cancer: WHO analgesic ladder, opioid rotation, adjuvant therapy",
      "Palliative care vs curative treatment: nursing goals, advance directives, DNR",
      "Cancer survivorship: follow-up care, fear of recurrence, rehabilitation",
    ],
    "Burns & Wound Management": [
      "Burn assessment: rule of nines, Lund-Browder chart, Parkland formula for fluid resuscitation",
      "Burn depth classification: superficial, partial thickness, full thickness — healing potential",
      "Inhalation injury: signs, intubation, carbonaceous sputum, bronchoscopy findings",
      "Wound healing phases: inflammatory, proliferative, remodeling — nursing interventions",
      "Wound assessment: measurement, documentation, wound bed classification",
      "Negative pressure wound therapy (wound VAC): indications, application, troubleshooting",
      "Pressure injury staging: categories 1-4, unstageable, deep tissue injury — prevention",
      "Skin grafts: split thickness vs full thickness, donor site care, graft take assessment",
    ],
    "Hematological Disorders": [
      "Anemia types: iron-deficiency, B12/folate deficiency, aplastic, hemolytic — differential diagnosis",
      "Sickle cell disease: vaso-occlusive crisis management, hydroxyurea, transfusion therapy",
      "Thalassemia: pathophysiology, blood transfusion, iron chelation, genetic counseling",
      "Disseminated intravascular coagulation (DIC): pathophysiology, labs, treatment",
      "Deep vein thrombosis: risk factors, anticoagulation, compression therapy, pulmonary embolism",
      "Hematological malignancies: leukemia, lymphoma, myeloma — assessment and treatment",
      "Blood transfusion nursing care: type and crossmatch, reactions, emergency protocol",
      "Bone marrow transplant: conditioning, engraftment, GvHD monitoring and management",
    ],
    "Infectious Diseases": [
      "Tuberculosis: DOT strategy, isoniazid side effects, sputum collection, contact screening",
      "HIV/AIDS: staging (CD4 count), ART adherence, opportunistic infection prevention",
      "Dengue fever: clinical phases, NS1 antigen, warning signs, fluid management",
      "Malaria: Plasmodium species, chloroquine resistance, ACT therapy, mosquito prevention",
      "COVID-19: respiratory support, prone positioning, vaccination, post-acute sequelae",
      "Antimicrobial stewardship: appropriate use, resistance patterns, hand hygiene compliance",
      "Sepsis: qSOFA criteria, Surviving Sepsis Campaign bundles, organ dysfunction monitoring",
      "Infection control: standard precautions, transmission-based precautions, PPE selection",
    ],
    "Critical Care Nursing": [
      "Hemodynamic monitoring: arterial line, CVP, PA catheter — interpretation and nursing care",
      "Mechanical ventilation: modes (AC, SIMV, PRVC, APRV), weaning protocols, ventilator alarms",
      "Vasoactive drip titration: norepinephrine, dobutamine, milrinone — dose ranges, monitoring",
      "Sepsis management: early goal-directed therapy, fluid resuscitation, antibiotic timing",
      "ARDS: Berlin definition, lung-protective ventilation, prone positioning, ECMO",
      "Shock types: distributive, cardiogenic, hypovolemic, obstructive — differential management",
      "Central line placement and maintenance: insertion, dressing changes, CLABSI prevention",
      "ICU delirium: CAM-ICU assessment, prevention strategies, pharmacological management",
    ],
    "Emergency & Disaster Nursing": [
      "Triage systems: START triage, ESI, Manchester — rapid patient categorization",
      "Cardiac arrest management: BLS/ACLS algorithms, defibrillation, post-cardiac arrest care",
      "Anaphylaxis: epinephrine administration, airway management, monitoring",
      "Status epilepticus: benzodiazepine protocol, airway protection, long-term seizure control",
      "Acute poisoning: antidotes, decontamination, enhanced elimination, supportive care",
      "Disaster preparedness: ICS, hospital emergency response codes, surge capacity",
      "Trauma assessment: primary survey (ABCDE), secondary survey, stabilization",
      "Mass casualty incident: START triage, resource allocation, psychological first aid",
    ],
    "Renal & Transplant Nursing": [
      "Acute kidney injury: KDIGO criteria, renal replacement therapy indications",
      "Continuous renal replacement therapy (CRRT): modality selection, anticoagulation, nursing care",
      "Kidney transplant: preoperative workup, intraoperative phase, rejection types",
      "Post-transplant immunosuppression: tacrolimus, cyclosporine, MMF — therapeutic drug monitoring",
      "Transplant complications: infection, malignancy, cardiovascular disease, allograft dysfunction",
      "Vascular access for dialysis: AV fistula, AV graft, central venous catheter — care and assessment",
      "Hemodialysis complications: disequilibrium syndrome, hypotension, muscle cramps, air embolism",
      "Peritoneal dialysis: catheter exit site care, peritonitis diagnosis, exchange technique",
    ],
    "End-of-Life & Palliative Care": [
      "Palliative care principles: symptom management, holistic care, goals of care conversation",
      "Pain assessment in palliative care: pain scales, barriers to reporting, equianalgesic dosing",
      "Dyspnea management: opioid therapy, positioning, oxygen, fan therapy",
      "Terminal restlessness: assessment, pharmacological management, environmental modification",
      "Advance care planning: living will, health care proxy, POLST/MOLST",
      "Death and dying: Kübler-Ross model, cultural rituals, Filipino bereavement practices",
      "Hospice care: eligibility criteria, interdisciplinary team, home-based hospice nursing",
      "Bereavement support: complicated grief, family follow-up, self-care for healthcare workers",
    ],
  },
  "nlp-v": {
    "Therapeutic Communication": [
      "Therapeutic vs non-therapeutic techniques: active listening, reflection, summarization",
      "Maslow's hierarchy of needs: physiological, safety, belonging, esteem, self-actualization",
      "Communication barriers: cultural differences, age, physical limitations, psychiatric symptoms",
      "Building therapeutic rapport: genuineness, unconditional positive regard, empathy",
      "Non-verbal communication: proxemics, kinesics, paralinguistics — interpretation in mental health",
      "Motivational interviewing: OARS, change talk, rolling with resistance",
      "Documentation of psychiatric interactions: objective language, SOAPIE format, legal considerations",
      "Self-disclosure in therapeutic relationships: boundaries, appropriate use, risks",
    ],
    "Anxiety & Mood Disorders": [
      "Generalized anxiety disorder: DSM-5 criteria, cognitive distortions, treatment approaches",
      "Panic disorder: agoraphobia, interoceptive exposure, benzodiazepine management",
      "Major depressive disorder: neurobiological theories, PHQ-9, treatment algorithm",
      "Bipolar disorder: manic vs depressive episodes, mood stabilizers, lithium monitoring",
      "Dysthymia (persistent depressive disorder): chronic course, combined pharmacotherapy",
      "Postpartum depression: screening (Edinburgh scale), treatment options, breastfeeding considerations",
      "Seasonal affective disorder: light therapy, vitamin D, adjunctive treatments",
      "Anxiety and depression comorbidity: differential diagnosis, integrated treatment planning",
    ],
    "Psychotic Disorders": [
      "Schizophrenia: positive vs negative symptoms, Schneider's first-rank symptoms",
      "Schizoaffective disorder: criteria, differential diagnosis, mood stabilizer + antipsychotic",
      "Brief psychotic disorder: diagnostic criteria, prognosis, stress-related onset",
      "Antipsychotic medications: typical vs atypical, EPS, metabolic syndrome, NMS",
      "Clozapine: agranulocytosis monitoring, REMS program, refractory schizophrenia",
      "Disorganized thinking: thought blocking, tangentiality, loose associations — nursing assessment",
      "Paranoid ideation: therapeutic approach, validation vs challenging, safety considerations",
      "Psychoeducation for schizophrenia: illness awareness, relapse prevention, family intervention",
    ],
    "Personality Disorders": [
      "Cluster A (odd-eccentric): paranoid, schizoid, schizotypal — traits and nursing approach",
      "Cluster B (dramatic-erratic): borderline, narcissistic, histrionic, antisocial",
      "Borderline personality disorder: emotional dysregulation, DBT, suicide risk management",
      "Narcissistic personality: grandiosity, fragile self-esteem, therapeutic relationship challenges",
      "Antisocial personality: disregard for rules, manipulation, legal and ethical dilemmas",
      "Ego-syntonic vs ego-dystonic personality traits: patient insight and treatment motivation",
      "Boundary setting in psychiatric nursing: consistency, limits, therapeutic neutrality",
      "Schema therapy and mentalization-based treatment for personality disorders",
    ],
    "Substance Use Disorders": [
      "Alcohol use disorder: withdrawal timeline, CIWA-Ar assessment, benzodiazepine protocol",
      "Opioid use disorder: MAT (methadone, buprenorphine), overdose reversal (naloxone)",
      "Stimulant intoxication (methamphetamine, cocaine): agitation, psychosis, cardiovascular risk",
      "Substance withdrawal seizures: alcohol, benzodiazepines — monitoring and prevention",
      "Dual diagnosis: substance use + psychiatric disorder, integrated treatment models",
      "Stages of change (Prochaska): precontemplation, contemplation, preparation, action, maintenance",
      "Motivational interviewing for addiction: ambivalence, change talk, non-judgmental stance",
      "Relapse prevention: triggers, coping skills, high-risk situations, support systems",
    ],
    "Psychopharmacology": [
      "SSRIs: mechanism, onset of action, sexual side effects, serotonin syndrome",
      "Benzodiazepines: GABA-A mechanism, tolerance, dependence, tapering protocols",
      "Lithium: therapeutic range, toxicity, monitoring (TSH, Cr, Na), patient education",
      "Antipsychotics: D2 blockade, EPS (dystonia, akathisia, tardive dyskinesia), metabolic effects",
      "Mood stabilizers: valproate (hepatotoxicity, teratogenicity), carbamazepine (CYP450 induction)",
      "Anticholinergic medications: dry mouth, urinary retention, constipation, delirium risk in elderly",
      "Drug interactions in psychopharmacology: CYP450 system, serotonergic drugs, QTc prolongation",
      "Medication adherence: barriers, long-acting injectables, psychoeducation strategies",
    ],
    "Crisis & Suicide Intervention": [
      "Suicide risk assessment: C-SSRS, ideation vs intent vs plan, lethality assessment",
      "Crisis intervention model: safety assessment, de-escalation, disposition planning",
      "Self-harm vs suicidal behavior: distinction,动机, nursing management",
      "De-escalation techniques: verbal strategies, therapeutic use of silence, environmental control",
      "Lethal means counseling: restricting access to firearms, medications, sharp objects",
      "Postvention: responding to a patient suicide, staff support, family notification",
      "Safety planning: Stanley & Brown model, coping cards, emergency contacts",
      "Crisis hotlines and community resources: role in acute psychiatric emergencies",
    ],
    "Child & Adolescent Psychiatry": [
      "ADHD: diagnostic criteria, stimulant medications, behavioral interventions, school accommodations",
      "Autism spectrum disorder: early signs, applied behavior analysis, communication strategies",
      "Conduct disorder vs oppositional defiant disorder: differential diagnosis, management",
      "Pediatric depression and anxiety: CBT for youth, SSRIs in children, family involvement",
      "Eating disorders: anorexia nervosa (refeeding syndrome risk), bulimia nervosa, binge eating",
      "Pediatric bipolar disorder: diagnostic challenges, mood stabilizers, family psychoeducation",
      "Trauma-informed care in adolescents: ACEs, EMDR, TF-CBT, safe environments",
      "Gender dysphoria in youth: assessment, puberty blockers, mental health support",
    ],
  },
}

export function getTopicsForArea(area: string): string[] {
  return Object.keys(CONCEPT_CHECKLISTS[area] ?? {})
}

export function getConceptsForTopic(area: string, topic: string): string[] {
  return CONCEPT_CHECKLISTS[area]?.[topic] ?? []
}
